# Netlify Configuration for Food Ninja PWA
[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY" 
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=self, microphone=(), geolocation=()"

# PWA Assets Cache
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.css" 
  [headers.values]
    Cache-Control = "public, max-age=86400"

# API Redirects to Render Backend  
[[redirects]]
  from = "/predict"
  to = "https://nckh-nutrition-food.onrender.com/predict"
  status = 200
  force = true

[[redirects]]
  from = "/chat"
  to = "https://nckh-nutrition-food.onrender.com/chat"
  status = 200
  force = true
  
  [[redirects]]
  from = "/ask_ai"
  to = "https://nckh-nutrition-food.onrender.com/ask_ai"
  status = 200
  force = true

# SPA Fallback for PWA
[[redirects]]
  from = "/*"
  to = "/app.html"
  status = 200
