services:
  - type: web
    name: foodninja-backend-latest
    env: python
    plan: free
    region: oregon
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 300 --max-requests 1000 --max-requests-jitter 100
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      
      - key: WEB_CONCURRENCY
        value: 1
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /health
